---
#--------------------------------------------------
#  发布 Astro
#--------------------------------------------------
#

name: Deploy Astro

on:
  push:
    branches: [astro]
    tags:
      - '*'

permissions:
  contents: write

jobs:
  npm:
    runs-on: ubuntu-latest
    steps:
      - name: 当前用户
        run: whoami
      - name: Checkout
        uses: actions/checkout@v3
      - name: Servon Deploy
        run: servon deploy astro --repo https://github.com/CofficLab/Kuaiyizhi --branch astro
